name: Node.js CI and Firebase Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Node.js and cache dependencies
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - run: npm ci

    # Build the Angular project
    - run: npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Install Firebase CLI
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Authenticate with Firebase
    - name: Authenticate with Firebase
      uses: google-github-actions/firebase-auth@v1
      with:
        credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    # Deploy to Firebase Hosting
    - name: Deploy to Firebase
      run: firebase deploy --only hosting
